modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-analytics-fog-module
name: Analytics Fog
description: Analytics-Fog enables the gateway to start analytics pipelines on the device. It also controls the data sharing with the cloud.
version: v3.0.0
type: add-on
tags:
  - analytics
  - fog
deploymentType: single
services:
  fog-agent:
    name: Fog Agent
    image: ghcr.io/senergy-platform/analytics-fog-agent:v2.0.10
  fog-master:
    name: Fog Master
    image: ghcr.io/senergy-platform/analytics-fog-master:v2.0.21
  fog-connector:
    name: Fog Connector
    image: ghcr.io/senergy-platform/analytics-fog-connector:v2.1.0

auxServices:
  operator:
    name: Analytics-Operator

auxImageSources:
  - "ghcr.io/senergy-platform/*"
  - "github.com/SENERGY-Platform/*"

inputGroups:
  cloud-settings:
    name: Cloud settings
  cloud-auth:
    name: Authentication
    group: cloud-settings
  cloud-mqtt:
    name: MQTT
    group: cloud-settings
  cloud-api:
    name: APIs
    group: cloud-settings
  local-settings:
    name: Local settings
  agent-settings:
    name: Agent
    group: local-settings
  master-settings:
    name: Master
    group: local-settings
  connector-settings:
    name: Connector
    group: local-settings
  
volumes:
  master-data: 
    - mountPoint: /data
      services:
        - fog-master
  agent-data: 
    - mountPoint: /data
      services:
        - fog-agent

dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: FOG_BROKER_HOST
          services:
            - fog-agent
            - fog-master
            - fog-connector
  github.com/SENERGY-Platform/mgw-cloud-proxy/mgw-module:
    version: "<v1.0.0"
    requiredServices:
      gateway:
        - refVar: PLATFORM_BROKER_HOST
          template: "{ref}"
          services:
            - fog-connector
        - refVar: MGW_CERT_MANAGER_URL
          template: "http://{ref}:8080/api"
          services:
            - fog-connector

configs:
  operatorTimeout:
    dataType: int
    value: 60
    targets:
      - refVar: CONTROL_OPERATOR_TIMEOUT
        services:
          - fog-agent
    userInput:
      type: number
      name: Timeout for starting and stopping the operator container
      group: agent-settings

  syncInterval:
    dataType: int
    value: 120
    targets:
      - refVar: SYNC_INTERVAL
        services:
          - fog-connector
    userInput:
      type: number
      name: Time in seconds to sync running operators with the platform
      group: connector-settings

  debug:
    dataType: string
    value: "false"
    options:
      - "true"
      - "false"
    targets:
      - refVar: DEBUG
        services:
          - fog-connector
          - fog-master
          - fog-agent
    userInput:
      type: text
      name: Debug mode
      group: local-settings

  data_dir:
    dataType: string
    value: "/data"
    targets:
      - refVar: DATA_DIR
        services:
          - fog-master
          - fog-agent
    userInput:
      type: text
      name: Data Directory
      group: local-settings

  db_path:
    dataType: string
    value: "/data/sqlite.db"
    targets:
      - refVar: DATABASE_PATH
        services:
          - fog-master
          - fog-agent
    userInput:
      type: text
      name: Path to Database
      group: local-settings

  platformBrokerPort:
    dataType: int
    value: 1883
    targets:
      - refVar: PLATFORM_BROKER_PORT
        services:
          - fog-connector

  fogBrokerPort:
    dataType: int
    value: 1881
    targets:
      - refVar: FOG_BROKER_PORT
        services:
          - fog-master
          - fog-agent

  moduleManagerUrl:
    dataType: string
    value: http://core-api/module-manager
    targets:
      - refVar: MODULE_MANAGER_URL
        services:
          - fog-agent

  operatorManager:
    dataType: string
    value: mgw
    targets:
      - refVar: CONTAINER_MANAGER
        services:
          - fog-agent