modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-analytics-fog-module
name: Analytics Fog
description: Analytics-Fog enables the gateway to start analytics pipelines on the device. It also controls the data sharing with the cloud.
version: v1.0.1
type: add-on
tags:
  - analytics
  - fog
deploymentType: single
services:
  fog-agent:
    name: Fog Agent
    image: ghcr.io/senergy-platform/analytics-fog-agent:latest
  fog-master:
    name: Fog Master
    image: ghcr.io/senergy-platform/analytics-fog-master:latest

volumes:
  master-data: 
    - mountPoint: /data
      services:
        - fog-master
  agent-data: 
    - mountPoint: /data
      services:
        - fog-agent

dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: BROKER_HOST
          services:
            - fog-agent
            - fog-master

configs:
  retriesOperatorStart:
    dataType: int
    value: 
    targets:
      - refVar: RETRIES_START_OPERATOR
        services:
          - fog-master
    userInput:
      type: int
      name: Number of retries to start operator

  retryTimeoutOperatorStart:
    dataType: int
    value: 
    targets:
      - refVar: TIMEOUT_START_OPERATOR
        services:
          - fog-master
    userInput:
      type: int
      name: Timeout between retries to start operator

  dataDirectory:
    value: /data
    targets:
      - refVar: DATA_DIR
        services:
          - fog-master
          - fog-agent

secrets:
# TODO: login data at connector
  auth:
    type: basic-auth
    targets:
      - refVar: USERNANE
        item: username
        services:
          - fog-master # TODO connector
      - refVar: PASSWORD
        item: password
        services:
          - fog-master # TODO connector
    userInput:
      name: Auth Credentials